apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 2
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: jackcaldwell/go-todo:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
          - name: web
            containerPort: 8080
