apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
spec:
  selector:
    matchLabels:
      app: go-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
        - name: go-demo
          image: 102469546157.dkr.ecr.eu-west-1.amazonaws.com/go-demo:ca10ed82ba139307141753ab4b9355bd3a9f0def
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
